# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6bfca3061a4c089c41000256e08350351f73e07b9289a0935fa0fbf188079ae59f9699e7ebd90e7355958fbf390e07ed020a806aaa63a4c908b26447c9778112

test:
  secret_key_base: 0f01c2ebce4f961820d4bf0c37ac79d21f61057ca9c74d41bf075f71491c485859bb99f3924ae772cf2b9b8b3b2b92939f34fafaf693bed06a3f4e4bb6e31a38

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
